### ISSUE TITLE
Failing to build Engine with limited file access rights

### ISSUE THREAD

**Issue by knanne** [ahdis/matchbox#113]
I'm trying to run matchbox engine in a cloud environment with limited access rights. My code fails to instantiate the engine due to underlying fhir validation engine building needing access to file system

Is this necessary if i'm only using the engine to transform? Can we somehow turn this off or catch the exception and continue?

```
Java Stack Trace: java.io.FileNotFoundException: ?/.fhir/packages/packages.ini (No such file or directory) at
java.base/java.io.FileOutputStream.open0(Native Method) at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298) at 
java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237) at java.base/java.io.FileOutputStream.<init>
(FileOutputStream.java:187) at function_handler_0//org.hl7.fhir.utilities.TextFile.stringToFile(TextFile.java:122) at 
function_handler_0//org.hl7.fhir.utilities.TextFile.stringToFile(TextFile.java:132) at 
function_handler_0//org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.<init>(FilesystemPackageCacheManager.java:128) at 
function_handler_0//org.hl7.fhir.validation.ValidationEngine.getPcm(ValidationEngine.java:967) at 
function_handler_0//org.hl7.fhir.validation.ValidationEngine.initContext(ValidationEngine.java:456) at 
function_handler_0//org.hl7.fhir.validation.ValidationEngine$ValidationEngineBuilder.fromNothing(ValidationEngine.java:356) at 
function_handler_0//ch.ahdis.matchbox.engine.MatchboxEngine$MatchboxEngineBuilder.getEngineR4(MatchboxEngine.java:108) 
```

**Comment by oliveregger** [comment]
similar problem here https://github.com/project-husky/husky/issues/61

**Comment by qligier** [comment]
Currently, the filesystem package cache manager is required by HAPI core.

With HAPI Core 5.6.971, it can only write to ~/.fhir or /var/lib/.fhir. Starting with 6.0.0, [a temp directory is also available](https://github.com/hapifhir/org.hl7.fhir.core/commit/0bbff8d14d60b2d12b0de96836dba3981cad4d7c) (C:/temp/.fhir or [java.io.tmpdir]/.fhir).

With minimal effort, we could add a constructor to FilesystemPackageCacheManager which takes a custom path, if one needs to write in a controlled directory.

Providing a no-op or memory implementation could be harder. (Not sure if a memory cache manager makes sense here)

**Comment by qligier** [comment]
@knanne Would writing to /tmp/.fhir solve the issue within your cloud environment? Since we're updating to FHIR Core 6.0.1, it will be possible in the next matchbox version.

**Comment by knanne** [comment]
@qligier (editing after research) yes that would probably work. Server blocks access to anyway file operations outside of logging to a /tmp path. 

Separate question - does the engine require network connection to obtain these files?

...sorry I accidentally closed the issue (on mobile)

**Comment by qligier** [comment]
Okay, that's great.
I think we should work on removing the requirement to a filesystem cache manager anyway, but it is a bit more work.

Good question, I have never tested, but it should be able to work without a network connection, if you supply the NPM packages. I'll open another issue to track that.
