### ISSUE TITLE
update to hapi-fhir v6.6.0 and fhir.core 6.0.1

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#115]
update to hapi-fhir v6.6.0 and fhir.core 6.0.1

next release of hapi-fhir targeted in 2023-08-17

**Comment by oliveregger** [comment]
need also to update the base packages:

hl7.fhir.uv.extensions.r4#1.0.0
hl7.terminology#5.1.0 | R4

**Comment by qligier** [comment]
Done in v3.3.0
