### ISSUE TITLE
Check if the engine can run without internet connection

### ISSUE THREAD

**Issue by qligier** [ahdis/matchbox#116]
I guess matchbox should work without internet connection, we should check that it does.

**Comment by oliveregger** [comment]
same for server with tx set to matchbox

**Comment by qligier** [comment]
The engine can run without internet connection, but you might need it for the following:

- loading packages from the package registry. This can be avoided by providing all package files;
- validating resources with complex IGs. This can be avoided in some cases by using Matchbox's own terminology server.
