### ISSUE TITLE
Multiprofile validation for 1 resource

### ISSUE THREAD

**Issue by TristanKEREVAL** [ahdis/matchbox#117]
Validation error for a profiled Bundle resource with 2 profiles possible for 1 entry slice.
Is it normal and will this be possible in future versions ?

 
Error message : 2 profiles found for entry resource. More than one is not supported at this time. (Type Resource: https://apifhir.annuaire.sante.fr/ws-sync/exposed/structuredefinition/practitionerRole-professionalRole-rass, https://apifhir.annuaire.sante.fr/ws-sync/exposed/structuredefinition/practitionerRole-organizationalRole-rass)

**Comment by oliveregger** [comment]
Is it the same discussion as here? https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/2.20profiles.20found.20for.20entry.20resource

This is currently no supported by the reference validator and since matchbox is depending on the java reference validator it is currently not supported.
