### ISSUE TITLE
Errors for display values should only be warnings

### ISSUE THREAD

**Issue by ziegm** [ahdis/matchbox#132]
The validator for all FHIR implementation guide should have this flag:
**display-issues-are-warnings**
the default value for it should be true

**Comment by ziegm** [comment]
https://ehealthsuisse.ihe-europe.net/evs/report.seam?oid=1.3.6.1.4.1.12559.11.25.4.58133

**Comment by oliveregger** [comment]
https://gazelle.ihe.net/jira/projects/EHS/queues/issue/EHS-683

**Comment by oliveregger** [comment]
Details Validation Results Bundle / 2-7-MedicationCard
L0: Line[0] Col[0]:
Validation for profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard|4.0.0-ballot (2023-06-29T14:57:50+02:00) with packages: hl7.fhir.xver-extensions#4.0, hl7.fhir.r4.core#4.0.1, hl7.terminology#5.1.0, hl7.fhir.uv.extensions.r4#1.0.0, ihe.formatcode.fhir#1.1.0, ch.fhir.ig.ch-epr-term#2.0.9, ch.fhir.ig.ch-core#4.0.0-ballot, ch.fhir.ig.ch-emed#4.0.0-ballot Total: 7462ms powered by matchbox-engine 3.4.3, hapi-fhir 6.8.0 and org.hl7.fhir.core 6.0.22 validation parameters Parameters {doNative=false, hintAboutNonMustSupport=false, recursive=false, doDebug=false, assumeValidRestReferences=false, canDoNative=false, noExtensibleBindingMessages=false, noUnicodeBiDiControlChars=false, noInvariants=false, displayIssuesAreWarnings=true, wantInvariantsInMessages=false, txServer='http://tx.fhir.org', lang='null', snomedCT='null', fhirVersion='4.0.1', ig=ch.fhir.ig.ch-emed#4.0.0-ballot, questionnaireMode=CHECK, level=HINTS, mode=VALIDATION, securityChecks=false, crumbTrails=false, forPublication=false, jurisdiction=urn:iso:std:iso:3166#US, allowExampleUrls=false, locale='English', locations={}}
L32: Bundle.entry[0].resource.type:
None of the codings provided are in the value set 'DocumentEntry.typeCode' (http://fhir.ch/ig/ch-epr-term/ValueSet/DocumentEntry.typeCode|2.0.9), and a coding should come from this value set unless it has no suitable code (note that the validator cannot judge what is suitable) (codes = http://loinc.org#56445-0, http://snomed.info/sct#736378000)
L238: Bundle.entry[0].resource.entry[5].resource/*MedicationStatement/2-7-MedStatBeloczok*/.contained[0]/*Medication/Beloczok*/.code.coding[0]:
Code System URI 'urn:oid:2.51.1.1' is unknown so the code cannot be validated
L389: Bundle.entry[0].resource.entry[6].resource/*MedicationStatement/2-7-MedStatNorvasc*/.contained[0]/*Medication/Norvasc*/.code.coding[0]:
Code System URI 'urn:oid:2.51.1.1' is unknown so the code cannot be validated

**Comment by oliveregger** [comment]
alidation for profile http://fhir.ch/ig/ch-vacd/StructureDefinition/ch-vacd-document-immunization-administration|4.0.0-ballot (2023-06-29T17:17:43+02:00) with packages: hl7.fhir.xver-extensions#4.0, hl7.fhir.r4.core#4.0.1, hl7.terminology#5.1.0, hl7.fhir.uv.extensions.r4#1.0.0, ihe.formatcode.fhir#1.1.0, ch.fhir.ig.ch-epr-term#2.0.9, ch.fhir.ig.ch-core#4.0.0-ballot, hl7.fhir.uv.ips#1.0.0, ch.fhir.ig.ch-emed#4.0.0-ballot, ch.fhir.ig.ch-allergyintolerance#2.0.0-ballot, ch.fhir.ig.ch-vacd#4.0.0-ballot Total: 00:00:38.323 powered by matchbox-engine 3.4.3, hapi-fhir 6.8.0 and org.hl7.fhir.core 6.0.22 validation parameters Parameters {doNative=false, hintAboutNonMustSupport=false, recursive=false, doDebug=false, assumeValidRestReferences=false, canDoNative=false, noExtensibleBindingMessages=false, noUnicodeBiDiControlChars=false, noInvariants=false, displayIssuesAreWarnings=true, wantInvariantsInMessages=false, txServer='http://tx.fhir.org', lang='null', snomedCT='null', fhirVersion='4.0.1', ig=ch.fhir.ig.ch-vacd#4.0.0-ballot, questionnaireMode=CHECK, level=HINTS, mode=VALIDATION, securityChecks=false, crumbTrails=false, forPublication=false, jurisdiction=urn:iso:std:iso:3166#US, allowExampleUrls=false, locale='English', locations={}}
L24: Bundle.entry[0].resource/*Composition/0b89cbdd-ad7b-47bd-9128-609d292a8b92*/:
Resource has a language, but the XHTML does not have an lang or an xml:lang tag (needs both - see https://www.w3.org/TR/i18n-html-tech-lang/#langvalues)
L63: Bundle.entry[0].resource.section[0]:
Bundle.entry[0].resource.section[0]: Does not match slice 'originalRepresentation' (discriminator: code.coding.where((system = 'http://loinc.org') and (code = '55108-5')).exists())
Bundle.entry[0].resource.section[0]: Does not match slice 'administration' (discriminator: code.coding.where((system = 'http://loinc.org') and (code = '11369-6') and (display = 'Hx of Immunization')).exists())
Bundle.entry[0].resource.section[0]: Does not match slice 'medicalproblems' (discriminator: code.coding.where((system = 'http://loinc.org') and (code = '11450-4') and (display = 'Problem list Reported')).exists())
Bundle.entry[0].resource.section[0]: Does not match slice 'pastillnesses' (discriminator: code.coding.where((system = 'http://loinc.org') and (code = '11348-0') and (display = 'Hx of Past illness')).exists())
Bundle.entry[0].resource.section[0]: Does not match slice 'allergyintolerances' (discriminator: code.coding.where((system = 'http://loinc.org') and (code = '48765-2') and (display = 'Allergies and adverse reactions Document')).exists())
Bundle.entry[0].resource.section[0]: Does not match slice 'laboratory-serology' (discriminator: code.coding.where((system = 'http://loinc.org') and (code = '18727-8') and (display = 'Serology studies (set)')).exists())
Bundle.entry[0].resource.section[0]: Does not match slice 'annotation' (discriminator: code.coding.where((system = 'http://loinc.org') and (code = '48767-8') and (display = 'Annotation comment Imp')).exists())
L65: Bundle.entry[0].resource.section[0].extension[0]:
Unknown extension http://hcisolutions.ch/ig/ig-hci-vacd/StructureDefinition/hci-vac-ext-originform
L65: Bundle.entry[0].resource/*Composition/0b89cbdd-ad7b-47bd-9128-609d292a8b92*/.section[0].extension[0]:
Unknown extension http://hcisolutions.ch/ig/ig-hci-vacd/StructureDefinition/hci-vac-ext-originform
L67: Bundle.entry[0].resource.section[0].extension[0].value.ofType(canonical):
Canonical URL 'http://hcisolutions.ch/ig/ig-hci-vacd/Questionnaire/VaccinationHPVForm' does not resolve
L67: Bundle.entry[0].resource/*Composition/0b89cbdd-ad7b-47bd-9128-609d292a8b92*/.section[0].extension[0].value.ofType(canonical):
Canonical URL 'http://hcisolutions.ch/ig/ig-hci-vacd/Questionnaire/VaccinationHPVForm' does not resolve
L72: Bundle.entry[0].resource.section[0].code.coding[0]:
Der Displayname f\u00fcr http://loinc.org#81222-2 sollte einer von ''Consultation note - recommended C-CDA R2.0 and R2.1 sections' or 'Consult note C-CDA R2.0+2.1 Sections'' anstelle von 'Consultation note' sein. (from Tx-Server) for 'http://loinc.org#81222-2'
L72: Bundle.entry[0].resource/*Composition/0b89cbdd-ad7b-47bd-9128-609d292a8b92*/.section[0].code.coding[0]:
Der Displayname f\u00fcr http://loinc.org#81222-2 sollte einer von ''Consultation note - recommended C-CDA R2.0 and R2.1 sections' or 'Consult note C-CDA R2.0+2.1 Sections'' anstelle von 'Consultation note' sein. (from Tx-Server) for 'http://loinc.org#81222-2'
L152: Bundle.entry[5].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]:
Bundle.entry[5].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]: Does not match slice 'EPR-SPID' (discriminator: $this.where(system = 'urn:oid:2.16.756.5.30.1.127.3.10.3').exists())
Bundle.entry[5].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]: Does not match slice 'AHVN13' (discriminator: $this.where(system = 'urn:oid:2.16.756.5.32').exists())
Bundle.entry[5].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]: Does not match slice 'LocalPid' (discriminator: $this.where(type.coding.where((system = 'http://terminology.hl7.org/CodeSystem/v2-0203') and (code = 'MR')).exists()).exists())
Bundle.entry[5].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]: Does not match slice 'insuranceCardNumber' (discriminator: $this.where(system = 'urn:oid:2.16.756.5.30.1.123.100.1.1.1').exists())
L152: Bundle.entry[0].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]:
Bundle.entry[0].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]: Does not match slice 'EPR-SPID' (discriminator: $this.empty())
Bundle.entry[0].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]: Does not match slice 'AHVN13' (discriminator: $this.empty())
Bundle.entry[0].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]: Does not match slice 'LocalPid' (discriminator: $this.where(type.coding.where((system = 'http://terminology.hl7.org/CodeSystem/v2-0203') and (code = 'MR')).exists()).exists())
Bundle.entry[0].resource.entry[1].resource/*Patient/dc2afeaa-3f75-4217-88f6-9d7e866f0559*/.identifier[1]: Does not match slice 'insuranceCardNumber' (discriminator: $this.where(system = 'urn:oid:2.16.756.5.30.1.123.100.1.1.1').exists())
L270: Bundle.entry[0].resource.entry[5].resource/*AllergyIntolerance/cea49dd7-1b26-43ae-9fdf-3352d17f6c19*/.code:
Wrong Display Name 'Keine Allergie bekannt' for http://snomed.info/sct#716186003 - should be one of 3 choices: 'No known allergy (situation)', 'No known allergy' or 'NKA - no known allergy' (for the language(s) 'en') (from Tx-Server)
L271: Bundle.entry[5].resource/*AllergyIntolerance/cea49dd7-1b26-43ae-9fdf-3352d17f6c19*/.code.coding[0]:
Wrong Display Name 'Keine Allergie bekannt' for http://snomed.info/sct#716186003 - should be one of 3 choices: 'No known allergy (situation)', 'No known allergy' or 'NKA - no known allergy' (for the language(s) 'en') (from Tx-Server) for 'http://snomed.info/sct#716186003'

**Comment by oliveregger** [comment]
set in application.yaml
