### ISSUE TITLE
feature request: gazelle - connect matchbox through new validation-service API

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#141]
### Background

gazelle has integrated matchbox with the $validate FHIR operation with the Gazelle FHIR Validator R4, see example:

[CH EMED Medication Card Document](https://ehealthsuisse.ihe-europe.net/GazelleFhirValidatorR4/validators/displayResourceValidator.seam?id=1.3.6.1.4.1.12559.11.1.2.1.15.50), note that the following parameters have to been set:

- Execute schema validation ? false
- Execute schematron validation ? false
- **Use IG FHIR Server ? true**
- **URL http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard**

implementation is done in [net.ihe.gazelle.fhir.validator.validation.peripherals.ws.IGFhirServerClientImpl](https://gitlab.inria.fr/gazelle/applications/test-execution/validator/FhirValidator/-/blob/master/Fhir-Validator-Validation/Fhir-Validator-Validation-Peripherals/src/main/java/net/ihe/gazelle/fhir/validator/validation/peripherals/ws/IGFhirServerClientImpl.java)

this integration works very well, however it has two disadvantages
1. profile configuration needs to be done manually, matchbox enables to list al profiles/ig's which are available
2. additional validation parameters which matchbox offers (eg txServer, displayIssuesAreWarnings) cannot be configured

all of those information can be accessed over the OperationDefintion for [$validate](https://ehealthsuisse.ihe-europe.net/matchboxv3/fhir/OperationDefinition/-s-validate)

### gazelle FHIR Validation API
gazelle has incorporated a new [validation service API](https://gitlab.inria.fr/gazelle/library/validation-service-api):
This project is a library that provides all required APIs to build and integrate
a new validation service with Gazelle Test Bed.

if matchbox implements this API, a dynamically configuration could be adapted, and other clients could then call also directly matchbox validation if they don't want to use the FHIR $validate API but use the EVSClient API for validation like described [here](
https://gitlab.inria.fr/gazelle/applications/test-execution/validator/EVSClient/-/blob/master/EVSClient-ejb/src/main/resources/swagger/gazelletestbed-gazelle-evs_client_api-3.0-resolved.yaml)

The swagger description is located [here](https://app.swaggerhub.com/apis/gazelletestbed/gazelle-evs_client_api/3.0#/Validation/createValidation)

(don't know if a bridge is already implemented).

**Comment by oliveregger** [comment]
matchbox gui validate should then also to do the call to new validation api (support both)

**Comment by oliveregger** [comment]
http validator from gazelle uses this new logic too:

https://gitlab.inria.fr/gazelle/applications/test-execution/validator/http-validator

**Comment by oliveregger** [comment]
https://preprod.ihe-europe.net/

**Comment by oliveregger** [comment]
http validator:

add to docker file the following

gazelle/http-validator/http-validator-service

ENV GZL_PROFILE_REPOSITORY_PATH=/opt/http-validator/validationProfiles
ENV GZL_PROFILE_CACHE_MAX_ELEMENTS=50
ENV GZL_TOKEN_API_URL=http://localhost:8082
ENV APPLICATION_URL=http://localhost:8080/http-validator

then afterwards:

 docker build -t validator .

port 8080 needs to be exposed

http script attached (as http.txt, rename to http)

[http.txt](https://github.com/ahdis/matchbox/files/13787443/http.txt)

**Comment by oliveregger** [comment]
It would be nice to have additional info on the "Additional Metadata Matchbox QLIG-local" all values which we provide in hte operation outcome (a lot a are already there):

```json

  "extension": [ {
      "url": "http://matchbox.health/validiation",
      "extension": [ {
        "url": "profile",
        "valueUri": "http://hl7.org/fhir/StructureDefinition/Patient"
      }, {
        "url": "profileVersion",
        "valueUri": "4.0.1"
      }, {
        "url": "profileDate",
        "valueDateTime": "2019-11-01T09:29:23+11:00"
      }, {
        "url": "total",
        "valueDuration": {
          "value": 39,
          "unit": "ms"
        }
      }, {
        "url": "validatorVersion",
        "valueString": "powered by matchbox 3.5.4, hapi-fhir 6.10.0 and org.hl7.fhir.core 6.1.16"
      }, {
        "url": "ig",
        "valueString": "hl7.fhir.r4.core#4.0.1"
      }, {
        "url": "hintAboutNonMustSupport",
        "valueBoolean": false
      }, {
        "url": "recursive",
        "valueBoolean": false
      }, {
        "url": "showMessagesFromReferences",
        "valueBoolean": false
      }, {
        "url": "doDebug",
        "valueBoolean": false
      }, {
        "url": "assumeValidRestReferences",
        "valueBoolean": false
      }, {
        "url": "canDoNative",
        "valueBoolean": false
      }, {
        "url": "noExtensibleBindingMessages",
        "valueBoolean": false
      }, {
        "url": "noUnicodeBiDiControlChars",
        "valueBoolean": false
      }, {
        "url": "noInvariants",
        "valueBoolean": false
      }, {
        "url": "displayIssuesAreWarnings",
        "valueBoolean": true
      }, {
        "url": "wantInvariantsInMessages",
        "valueBoolean": false
      }, {
        "url": "doImplicitFHIRPathStringConversion",
        "valueBoolean": false
      }, {
        "url": "securityChecks",
        "valueBoolean": false
      }, {
        "url": "crumbTrails",
        "valueBoolean": false
      }, {
        "url": "forPublication",
        "valueBoolean": false
      }, {
        "url": "httpReadOnly",
        "valueBoolean": false
      }, {
        "url": "allowExampleUrls",
        "valueBoolean": false
      }, {
        "url": "txServer",
        "valueUri": "http://localhost:8081/matchboxv3/fhir"
      }, {
        "url": "lang"
      }, {
        "url": "snomedCT"
      }, {
        "url": "fhirVersion",
        "valueString": "4.0.1"
      }, {
        "url": "ig",
        "valueString": "hl7.fhir.r4.core#4.0.1"
      }, {
        "url": "locale",
        "valueString": "English"
      }, {
        "url": "jurisdiction",
        "valueString": "urn:iso:std:iso:3166#CH"
      }, {
        "url": "sessionId",
        "valueString": "211057106"
      }, {
        "url": "package",
        "valueString": "hl7.fhir.xver-extensions#4.0"
      }, {
        "url": "package",
        "valueString": "hl7.fhir.r4.core#4.0.1"
      }, {
        "url": "package",
        "valueString": "hl7.fhir.uv.extensions.r4#1.0.0"
      }, {
        "url": "package",
        "valueString": "hl7.terminology#5.4.0"
      } ]
    } ],

```

see also https://github.com/ahdis/matchbox/pull/194

**Comment by qligier** [comment]
Use the profile name instead of URL.
Allow Gazelle to filter by IG.

**Comment by oliveregger** [comment]
For the profile name we could maybe use NpmPackageVersionResourceEntity FileName in MatchboxPackageInstallerImpl

**Comment by oliveregger** [comment]
private org.hl7.fhir.r5.model.Resource loadPackageEntity(NpmPackageVersionResourceEntity contents) {

**Comment by qligier** [comment]
Also return the StructureDefinition title, IG title and version in the $validate OperationDefinition (add extensions to the targetProfile).
