### ISSUE TITLE
FHIR IG installation on server

### ISSUE THREAD

**Issue by dattachandan** [ahdis/matchbox#142]
Hi team, I can see the installed IGs on the public server, is there some instructions to import a custom published IG pack (as tgz?) to a local development server? Can the package URL be a local tgz file for the IG pack or included through any .env or yaml file?

![image](https://github.com/ahdis/matchbox/assets/2154248/62e26252-1c07-4d4f-be86-db3b7a873c0e)

**Comment by oliveregger** [comment]
@dattachandan you can configure it multiple ways:

specify in applicationyyaml which you provide during startup the different ig's, see an example here:
https://github.com/ahdis/matchbox/blob/main/matchbox-server/with-preload/application.yaml

if you don't put an url, the fhir package servers will be searched

url can bei either:
- http/https to a package
- file: if you provide the tgz by file
- classpath: if you build your own derived project and provide it in the classpath

if your local server is already running and you do not want to restart it,
you can provide it trough the GUI (make a port forward in vscode for example) or
use an API call see [ig.http](https://github.com/ahdis/matchbox/blob/main/matchbox-server/ig.http)

**Comment by oliveregger** [comment]
@dattachandan can we close this?

**Comment by dattachandan** [comment]
> @dattachandan can we close this?

Yep, will try with the NZ profile pack and update if there are issues with the tgz import

**Comment by dattachandan** [comment]
Closed
