### ISSUE TITLE
Validation shows no error despite not coforming MedicationCard

### ISSUE THREAD

**Issue by ziegm** [ahdis/matchbox#15]
[Medication Card document](https://github.com/ehealthsuisse/ch-emed/blob/validation/input/examples/bundle/medicationcard.json) which isn't conform to the profile

validator does not show error:
* [do validation](https://github.com/ehealthsuisse/ch-emed/blob/validation/validation.http)
* [validation result](https://github.com/ehealthsuisse/ch-emed/blob/validation/validationresult.json)

validation by IG Publisher results in the following error:
`error | Bundle.entry:Composition: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard)`

* see QA [here](http://build.fhir.org/ig/ehealthsuisse/ch-emed/branches/validation/qa.html#_scratch_ig-build-temp-CHRP4N_repo_input_examples_bundle_medicationcard)
* see also EVS Client [here](https://ehealthsuisse.ihe-europe.net/EVSClient/detailedResult.seam?type=FHIR&oid=1.3.6.1.4.1.12559.11.25.1.1352505)

**Comment by oliveregger** [comment]
The Composition is checked in the bundle, and the conformsTo Function is called for the first entry Composition with http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-composition-medicationcard. However only the base Composition is checked, but not the conformance to the referenced Profile (Patient and MedicationStatment are not correct to their respective profiles)

**Comment by oliveregger** [comment]
related to https://github.com/hapifhir/org.hl7.fhir.core/pull/676

**Comment by oliveregger** [comment]
error is now added:


>       "severity": "error",
>       "code": "processing",
>       "diagnostics": "Bundle.entry:Composition: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard)",
>       "location": [
>         "Bundle",
>         "Line 1, Col 2"
>       ]

and in addition the slicing info why it has failed is added as information:

> his element does not match any known slice defined in the profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard Slice info: 1.) Bundle.entry[0]: Does not match slice 'Composition' 2.) Bundle.entry[0]: Bundle.entry[1].resource.ofType(Patient): Patient.identifier: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-patient-epr) 3.) Bundle.entry[0]: Bundle.entry[3].resource.ofType(MedicationStatement): MedicationStatement.identifier: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationstatement-card) 4.) Bundle.entry[0]: Bundle.entry[3].resource.ofType(MedicationStatement).status: Value is 'active' but must be 'completed' 5.) Bundle.entry[0]: Bundle.entry[4].resource.ofType(MedicationStatement).dosage[1]: This element does not match any known slice  defined in the profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationstatement-card and slicing is CLOSED: Bundle.entry[4].resource.ofType(MedicationStatement).dosage[1]: Does not match slice 'nonstructured', Bundle.entry[4].resource.ofType(MedicationStatement).dosage[1]: Details for Bundle.entry[4].resource.ofType(MedicationStatement) matching against Profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-nonstructured, Bundle.entry[4].resource.ofType(MedicationStatement).dosage[1]: Does not match slice 'structurednormal', Bundle.entry[4].resource.ofType(MedicationStatement).dosage[1]: Details for Bundle.entry[4].resource.ofType(MedicationStatement) matching against Profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-structured-normal, Bundle.entry[4].resource.ofType(MedicationStatement).dosage[1]: Does not match slice 'structuredsplit', Bundle.entry[4].resource.ofType(MedicationStatement).dosage[1]: Details for Bundle.entry[4].resource.ofType(MedicationStatement) matching against Profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-dosage-structured-split 6.) Bundle.entry[0]: Bundle.entry[4].resource.ofType(MedicationStatement): MedicationStatement.identifier: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-medicationstatement-card) 7.) Bundle.entry[0]: Bundle.entry[4].resource.ofType(MedicationStatement).status: Value is 'active' but must be 'completed'

This is currently patched into the matchbox, but the next release of hapi-fhir should contain that in the FHIR validator also.
