### ISSUE TITLE
add onlyOneEngine and httpReadOnly to the validation operation outcome output

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#164]
add onlyOneEngine and httpReadOnly to the validation operation outcome output.

**Comment by qligier** [comment]
This was done with c93b113e.

Current output looks like:

> Validation for profile [http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document|1.0.0](http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document%7C1.0.0) (2023-11-23T17:43:37+01:00) with packages: hl7.fhir.xver-extensions#4.0, hl7.fhir.r4.core#4.0.1, hl7.fhir.uv.extensions.r4#1.0.0, fhir.dicom#2022.4.20221006, hl7.fhir.uv.ips#current, hl7.fhir.eu.laboratory#current, ihe.formatcode.fhir#1.1.0, ch.fhir.ig.ch-epr-term#2.0.9, ch.fhir.ig.ch-core#current, ch.fhir.ig.ch-lab-report#current, ch.fhir.ig.ch-elm#1.0.0 Total: 00:00:26.319 powered by matchbox 3.4.5, hapi-fhir 6.10.0 and org.hl7.fhir.core 6.1.16 validation parameters CliContext{doNative=false, hintAboutNonMustSupport=false, recursive=false, showMessagesFromReferences=false, doDebug=false, assumeValidRestReferences=false, canDoNative=false, noExtensibleBindingMessages=false, noUnicodeBiDiControlChars=false, noInvariants=false, displayIssuesAreWarnings=true, wantInvariantsInMessages=false, doImplicitFHIRPathStringConversion=false, htmlInMarkdownCheck=WARNING, txServer='http://localhost:8080/matchboxv3/fhir/', lang='null', snomedCT='null', fhirVersion='4.0.1', ig='ch.fhir.ig.ch-elm#1.0.0', questionnaireMode=CHECK, level=HINTS, mode=VALIDATION, securityChecks=false, crumbTrails=false, forPublication=false, allowExampleUrls=false, locale='English', locations={}, jurisdiction='urn:iso:std:iso:3166#GB', igsPreloaded=null, **onlyOneEngine**=false, **httpReadOnly**=true}
