### ISSUE TITLE
current is not set correctly to "latest" version

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#168]
when we have versions 4.0.0 and 4.0.0-xxxx 4.0.0 is not set as current, this should be changed if possible (our versioning might be not so good in this way, but hat how it was made for the latest ch ballot):

<img width="982" alt="image" src="https://github.com/ahdis/matchbox/assets/2414516/33918f78-731c-42c2-b1d0-9e090032c0f0">

**Comment by oliveregger** [comment]
see https://ehealthsuisse.ihe-europe.net/matchboxv3/#/igs

**Comment by oliveregger** [comment]
current is set during startup

**Comment by qligier** [comment]
~For R4 IGs, this is where the _current_ is set: https://github.com/ahdis/matchbox/blob/main/matchbox-server/src/main/java/ch/ahdis/fhir/hapi/jpa/validation/ImplementationGuideProviderR4.java#L370~
In fact, it is only for the search IGs operation.

**Comment by qligier** [comment]
The _current_ flag is stored in `NpmPackageVersionEntity.myCurrentVersion` (SQL: `NPM_PACKAGE_VER.CURRENT_VERSION`): https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-jpaserver-model/src/main/java/ca/uhn/fhir/jpa/model/entity/NpmPackageVersionEntity.java

The method that updates the flag when loading another IG version is `JpaPackageCache.updateCurrentVersionFlagForAllPackagesBasedOnNewIncomingVersion()`: https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/JpaPackageCache.java#L455

The version comparator is `PackageVersionComparator`: https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/packages/PackageVersionComparator.java

Looks like we have to override that last class.
