### ISSUE TITLE
ValueSet in server to be retrieved with GET $expand 

### ISSUE THREAD

**Issue by magp18** [ahdis/matchbox#20]
Hi!
I have a questionnaire, with multiple elements that refer / have answers linked to a ValueSet in the FHIR server (matchbox), however I am not able to retrieve the answerset when using the questionnaire toolkit (http://smartqedit4.azurewebsites.net/ts/). From my understanding, the toolkit is using a GET:
`GET {{host}}/ValueSet/valuesetID/$expand?_format=json HTTP/1.1`
but I am getting an OperationOutcome as: 
Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[ValueSet/valuesetID/$expand] with parameters [[_format]]

In the validation-ch-samples.http there is also the snippet:
`GET {{host}}/ValueSet/UnitCode/$expand HTTP/1.1

Accept: application/fhir+json
`

which throws the same error for me, just with parameters [[]] instead of _format

My question is: 
Is $expand not supported, or have I been using it wrong ?

**Comment by oliveregger** [comment]
@magp18 sorry I just came across your issue today. $expand is not supported on matchbox, we rely on the validator / terminology server to do the expansion during validation.
