### ISSUE TITLE
problem uploading ig

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#201]
on our test server we get an exception for uploading 
ch.fhir.ig.ch-elm  | 1.1.1

error [processing]:
HAPI-0389: Failed to call access method: org.springframework.dao.DataIntegrityViolationException: could not execute batch [Batch entry 0 insert into hfj_res_ver (res_deleted_at,res_encoding,res_version,has_tags,partition_date,partition_id,res_published,request_id,res_text,res_id,res_text_vc,res_type,res_ver,source_uri,res_updated,pid) values ((NULL),('JSON'),('R4'),('FALSE'),(NULL),(NULL),('2024-02-27 16:53:24.49+00'::timestamp),(NULL),(NULL),('36908'::int8),('{"resourceType":"Binary","contentType":"application/gzip","data":"H4..."}'),('Binary'),('1'::int8),(NULL),('2024-02-27 16:53:24.49+00'::timestamp),('39108'::int8)) was aborted: ERROR: value too long for type character varying(4000) Call getNextException to see other errors in the batch.] [insert into hfj_res_ver (res_deleted_at,res_encoding,res_version,has_tags,partition_date,partition_id,res_published,request_id,res_text,res_id,res_text_vc,res_type,res_ver,source_uri,res_updated,pid) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)]; SQL [insert into hfj_res_ver (res_deleted_at,res_encoding,res_version,has_tags,partition_date,partition_id,res_published,request_id,res_text,res_id,res_text_vc,res_type,res_ver,source_uri,res_updated,pid) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)]

**Comment by qligier** [comment]
This seems to be the relevant change: https://github.com/hapifhir/hapi-fhir/commit/7863f03c686766e5fcf9cc592612de1799ce7df7#diff-e9da0b2135ee0e5e3df21b869529cb0feee25d6d6e069e8db04d942bfcb3ff62

The limit was increased from 4000 to the maximum length that fits in 32 bits.
So the database was not migrated to the new schema.

**Comment by oliveregger** [comment]
thx, yes, updated the release notes.
