### ISSUE TITLE
Getting "Exception during Transform" with StructureMap/$transform operation on matchbox server

### ISSUE THREAD

**Issue by robeastwood-agency** [ahdis/matchbox#202]
Hello, I have been using the public matchbox test server (https://test.ahdis.ch/matchbox) for learning how to use FML to transform FHIR Bundle instances into CDA instances, in an Australian context.

I have authored 4 FML files that I have uploaded to the server, via individual POST operations, and then issuing a $transform operation using a Bundle instance as input. Over the last month or so, this has been working well, in that a CDA instance is being generated, albeit in gradually increasing increments as I learn more. For this, I'm using the VS Code REST Client extension.

From about 20 hours ago however, the transform operations are now returning a truncated CDA instance after about 10 lines (previously 100+ lines) with the last line including the text "_Exception during Transform_"; see response with header included:

```
HTTP/1.1 200 OK
Content-Type: application/fhir+xml;charset=UTF-8
Content-Length: 538
Date: Wed, 28 Feb 2024 06:45:29 GMT
Via: 1.1 google
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<ClinicalDocument 
  xmlns="urn:hl7-org:v3" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:sdtc="urn:hl7-org:sdtc">
  <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>
  <templateId root="1.2.36.1.2001.1001.100.149" extension="1.0"/>
  <templateId root="1.2.36.1.2001.1001.100.1002.218" extension="1.1"/>
  <templateId root="1.2.36.1.2001.1001.100.1002.32046" extension="1.0"/>
  <id root="2.25.83740161972982341976957999838084122579"/>
  <code coException during Transform
```

I have made some minor changes during this time frame in one of the chained StructureMaps, but I cannot figure out if my changes are related.

For convenience, refer to a `.http` file where I have made available the steps to reproduce:
https://github.com/robeastwood-agency/mapping-experiments/blob/main/matchbox-transform-simple.http

* this includes a $transform operation with a Bundle instance as a sibling file
* also included are GETs for the 4 chained StructureMaps as fyi

Also note that the exception is not limited to this Bundle but a number of others as well.

Any help pointing me in the right direction would be greatly appreciated. Thank you

Rob

**Comment by qligier** [comment]
Hi @robeastwood-agency 

We have upgraded that Matchbox instance to v3.6.0 yesterday around 17h UTC, that could explain the behaviour change.

It looks like a new bug in Matchbox:
```
2024-02-28 07:09:27.285 [http-nio-8080-exec-8] ERROR c.a.m.m.StructureMapTransformProvider [StructureMapTransformProvider.java:165] Transform exception
org.hl7.fhir.exceptions.FHIRException: Unknown Date format 'YYYYMMDDHHMMSS.UUUU[+|-ZZzz]'
        at org.hl7.fhir.r5.elementmodel.XmlParser.convertForDateFormatToExternal(XmlParser.java:553)
        at org.hl7.fhir.r5.elementmodel.XmlParser.composeElement(XmlParser.java:753)
        at org.hl7.fhir.r5.elementmodel.XmlParser.composeElement(XmlParser.java:773)
        at org.hl7.fhir.r5.elementmodel.XmlParser.compose(XmlParser.java:637)
        at ch.ahdis.matchbox.mappinglanguage.StructureMapTransformProvider.transform(StructureMapTransformProvider.java:162)
        at ch.ahdis.matchbox.mappinglanguage.StructureMapTransformProvider.manualInputAndOutput(StructureMapTransformProvider.java:130)
```

**Comment by robeastwood-agency** [comment]
Thank you so much @qligier

**Comment by qligier** [comment]
I have deployed the fix on https://test.ahdis.ch/matchbox

**Comment by robeastwood-agency** [comment]
Perfect! Thank you @qligier and @oliveregger for the fast resolution
