### ISSUE TITLE
Transform: support for target CDA observation.value as xsi:type CS?

### ISSUE THREAD

**Issue by robeastwood-agency** [ahdis/matchbox#205]
I'm attempting to transform FHIR CodeableConcept data to a CDA observation and cannot find a way to create an `observation.value` as `xsi:type="CS"`

Getting this error on $transform with:
```
Type 'CS' is not an acceptable type for 'value' on property Observation.value
```  
Long story short- not sure if this is a matter for matchbox, or the [core spec CDA logical model](https://build.fhir.org/ig/HL7/CDA-core-sd/), or how I am constructing the rule, or something else. So starting here...

#### Source:
Patient data with [HL7AU Patient extension for patient birth data accuracy](https://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-date-accuracy-indicator.html), with data like this, specifically the code value "AAA":
```
<extension url="http://hl7.org.au/fhir/StructureDefinition/date-accuracy-indicator">
    <valueCoding>
        <system value="https://healthterminologies.gov.au/fhir/CodeSystem/date-accuracy-indicator-1"/>
        <code value="AAA"/>
        <display value="Day, month and year are accurate"/>
    </valueCoding>
</extension>
```
And for the purposes of the transform this data is inside of a Bundle of type document, with the above inside the Patient resource.

#### Target
I'm trying to map this into a CDA observation class, according to our AU CDA specifications, which should look like this, which is legal against the XSD-based schema:
```
<entry typeCode="DRIV">
    <observation classCode="OBS" moodCode="EVN">
        <id root="D253216C-EFD0-11DF-A686-ADCCDFD72085" />
        <code xsi:type="CD" code="102.16234" codeSystem="1.2.36.1.2001.1001.101" codeSystemName="NCTIS Data Components" displayName="Date of Birth Accuracy Indicator"/>
        <value code="AAA" xsi:type="CS" /> <!-- note this line -->
    </observation>
</entry>
```

#### My map attempt
I have successfully mapped all of the above target CDA elements, including `observation.code` as `xsi:type="CD"`, but cannot get observation.value to work; I have tried this
```
valueCoding -> entry.observation as observation then {
    valueCoding.code as srccode -> observation.value = create('CS') as obsvalue then {
        srccode -> obsvalue.code = srccode "code";
     } "obsvalue";
}
```
Which upon transform, I get the error reported at the top.

I suspect that my map rule is reasonably close, as when I swap the XSI type to be CD (ie `create('CD')`) then the transform works to generate a observation.value element like this:
```
<observation classCode="OBS" moodCode="EVN">
    <id root="D253216C-EFD0-11DF-A686-ADCCDFD72085" />
    <code xsi:type="CD" code="102.16234" codeSystem="1.2.36.1.2001.1001.101" codeSystemName="NCTIS Data Components" displayName="Date of Birth Accuracy Indicator"/>
    <value code="AAA" xsi:type="CD" /> <!-- this line -->
</observation>
```
But this result then fails our schematrons, as the CD type expects other attributes, like codesystem.

Looking at the [core spec CDA logical model Observation class](https://build.fhir.org/ig/HL7/CDA-core-sd/StructureDefinition-Observation.html), it seems that `CS` is not explicitly an allowed type for `observation.value`, so that may be the problem. But a local validation using the FHIR validator against this package with observation.value as xsi:type="CS" did not fail.

Or maybe this is related to #189 somehow (edit 2024-03-04- that should be #196)

Thank you so much for looking at this long discussion, and any help you could offer will be fantastic.

**Comment by oliveregger** [comment]
The CDA specs reads as following:

3.1.13.1 | Observation.value :: ANY (0..*)
-- | --
  |   | Definition:Information that is assigned or determined by the observation action.Constraints: The Observation.value, if not otherwise constrained, can be of any data type.

3.1.13.1
[Observation](https://github.com/ahdis/matchbox/issues/205#Observation-cls).value :: [ANY](https://github.com/ahdis/infrastructure/datatypes/datatypes.htm#dt-ANY) (0..*)
 		
Definition:Information that is assigned or determined by the observation action.
Constraints: The Observation.value, if not otherwise constrained, can be of any data type.

**Comment by oliveregger** [comment]
@robeastwood-agency as you state, the CS is not included in the logical model of matchbox, see here:
https://ahdis.github.io/matchbox/cda-logical-model/StructureDefinition-Observation.html

and this leads to an exception while parsing (or also transformin):
org.hl7.fhir.exceptions.DefinitionException: Type 'CS' is not an acceptable type for 'value' on property Observation.value

i see two way out of this:

a) open a jira change and add a "propose a change" to https://hl7.org/cda/stds/core/2.0.0-sd-snapshot1/StructureDefinition-Observation.html, if this would be resolved we will update the cda matchbox logical model with it

b) we rebase our model to the current hl7 logical model and add support for the CS type until it is integrated for the hl7 model (like we do with ihe ... and other extensions).  see [#196](https://github.com/ahdis/matchbox/issues/196)

**Comment by robeastwood-agency** [comment]
Thank you so much for the considered review @oliveregger, and that makes perfect sense.

For either option, the HL7 international CDA model needs attention (or at least that's how I see it; whether they do too, it remains to be seen), so I will log a ticket as you suggest. 

And then in the meantime whether a patch is added to the current logical model for CS type in matchbox, I'll leave it up to you. In our current project, this item is not a high priority concern, so we could park it for now. It is in the realm of a nice to have and I would therefore not like to put this ahead of other matters that you have on your matchbox TODO list.

Thanks again!

**Comment by oliveregger** [comment]
@robeastwood-agency we will add support for it in the next release

**Comment by robeastwood-agency** [comment]
Thank you very much @oliveregger 

BTW, I haven't yet added a ticket on the core CDA spec as am having issues with my HL7 International JIRA account. However, the issue with CS does seem very related to this existing JIRA ticket: https://jira.hl7.org/browse/CDA-20779 (on which I will add a comment, as soon as my account permissions allow).

**Comment by robeastwood-agency** [comment]
This works perfectly; thank you. Closing as done.
