### ISSUE TITLE
Allow installing an IG from a single URL

### ISSUE THREAD

**Issue by qligier** [ahdis/matchbox#230]
In the interface, it would be nice to allow installing an IG from the URL of an online version. It's annoying filling the three fields each time.

E.g. https://build.fhir.org/ig/IHE/pharm-meow/branches/main/index.html, https://build.fhir.org/ig/IHE/pharm-meow/branches/main/ and https://build.fhir.org/ig/IHE/pharm-meow/branches/main/package.tgz could easily be resolved to `ihe.pharm.meow#0.1.0`, with the package.tgz in the same directory.

HTML parsing: the good part is:
```html
<button data-clipboard-text="http://profiles.ihe.net/PHARM/MEOW/ImplementationGuide/ihe.pharm.meow|0.1.0" title="Click to copy versioned URL" class="btn-copy"></button>
```

**Comment by qligier** [comment]
Can't implement that easily because of CORS, preventing the browser from fetching the HTML page.

**Comment by qligier** [comment]
We can create a proxy route in matchbox-server, or make a lambda on a free hosting if we want to implement that feature.

**Comment by oliveregger** [comment]
read the available package feeds and present that to the user? 

adding ig's through the gui should be the exception, mostly you would configure it directly in application.yml

**Comment by qligier** [comment]
> read the available package feeds and present that to the user?

We could try that, but we may have the same CORS issue. We could query the registry for published IGs, and the list of auto-built IGs.

> adding ig's through the gui should be the exception, mostly you would configure it directly in application.yml

For production, sure. But in dev, it may be a helpful feature.

**Comment by qligier** [comment]
The feature is not really helpful, won't be implemented
