### ISSUE TITLE
Don't return extensions url for validation 

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#237]
matchbox currently returns extensions url in the operation definition for $validate, see https://test.ahdis.ch/matchboxv3/fhir/OperationDefinition/-s-validate and in https://test.ahdis.ch/matchboxv3/gazelle/validation/profiles, we should filter them out because they cannot be used for validation

**Comment by qligier** [comment]
`StructureDefinition.type = Extension`
