### ISSUE TITLE
update to hl7.fhir.core 6.3.11

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#254]
we have validation issues with the hl7.fhir.core 6.3.5 version with the lastest ch-ig publications (which were done with IG Publisher and core version 6.3.7)

**Comment by TristanKEREVAL** [comment]
Validation problems are related to terminolgy validation : https://qualification.ihe-europe.net/evs/report.seam?oid=1.1.1.1.1.1.4.2160&standard=4

**Comment by oliveregger** [comment]
fixed in v3.8.6
