### ISSUE TITLE
internal terminology server does not validate 3 letter country codes

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#259]
we get error messages when three letter country codes are used:

 «Constraint failed: ch-addr-1: 'ISO Country Alpha-2 or ISO Country Alpha-3 code' (defined in http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-address)»

the constraint checks the member ship of https://hl7.org/fhir/R4/valueset-iso3166-1-3.html, however there is no computable expansion directly availabe and the constraint fails.

**Comment by qligier** [comment]
It should be supported by this code:
https://github.com/ahdis/matchbox/blob/3d5023bb701db8a5a1259acc3ab2755a0ae02e17/matchbox-server/src/main/java/ch/ahdis/matchbox/terminology/ValueSetCodeValidationProvider.java#L236-L244

We advertise support for `urn:iso:std:iso:3166` here:
https://github.com/ahdis/matchbox/blob/3d5023bb701db8a5a1259acc3ab2755a0ae02e17/matchbox-server/src/main/java/ch/ahdis/matchbox/interceptor/TerminologyCapabilitiesInterceptor.java#L68-L77

**Comment by oliveregger** [comment]
mmh, maybe memberOf is not using this code?

**Comment by oliveregger** [comment]
org.hl7.fhir.r5.terminologies.validation.VSCheckerException: Resolved system urn:iso:std:iso:3166 (v1.0.1), but the definition doesn't include any codes, so the code has not been validated

**Comment by oliveregger** [comment]
fixed in version 3.8.8
