### ISSUE TITLE
loading IG from package by filepath does not work

### ISSUE THREAD

**Issue by ralych** [ahdis/matchbox#26]
the following works:
hapi:
  fhir:
    implementationguides:
      cda:
        url: classpath:/hl7.fhir.cda-package.tgz
        name: hl7.fhir.cda
        version: 2.1.0

the following does not work:
hapi:
  fhir:
    implementationguides:
      cda:
        url: /<fs path to the package>/hl7.fhir.cda-package.tgz
        name: hl7.fhir.cda
        version: 2.1.0
possible could also be file:/<fs path to the package>/hl7.fhir.cda-package.tgz liek classpath:/...

**Comment by oliveregger** [comment]
with version 3.1.0 you have to prefix the url with file: (instead of classpath:) when you wan't to upload directly from a file
