### ISSUE TITLE
The provided url is not correct (remaining 'v3')

### ISSUE THREAD

**Issue by nriss** [ahdis/matchbox#263]
* On readme 

![image](https://github.com/user-attachments/assets/442dc5aa-ebde-40e1-bc49-1b299a80d056)

* On documentation

![image](https://github.com/user-attachments/assets/a5e0f254-1359-469a-9bb4-e9a5d7a6b033)
https://ahdis.github.io/matchbox/docker/

**Comment by qligier** [comment]
Hi Nicolas!
I'm unsure what the issue exactly is.
Are you saying the 'v3' should be removed? `/matchboxv3/` is still the default configuration:

https://github.com/ahdis/matchbox/blob/6780474c3db1ddc37fd5483dd6b38b1c93b86053/matchbox-server/src/main/resources/application.yaml#L32-L34

**Comment by nriss** [comment]
Ohh! Alright!
I used this config file that is not containing v3 in the context path : https://github.com/ahdis/matchbox/blob/6780474c3db1ddc37fd5483dd6b38b1c93b86053/matchbox-server/with-cda/application.yaml#L6

There is also an URL in the README which is not containing "v3" (in the display), I thought that you changed it recently
https://github.com/ahdis/matchbox/blob/6780474c3db1ddc37fd5483dd6b38b1c93b86053/README.md?plain=1#L56

Don’t have any preference about removing it or not personally

**Comment by oliveregger** [comment]
we have two test instances:

http://test.ahdis.ch/matchbox/ -> development instance, you can overwrite conformance resources or structure maps, there is one context

http://test.ahdis.ch/matchboxv3/ -> testing instance, all functionality is by ig (validation, transformation), you cannot update anymore directly conformance resources, just replace the whole ig.
