### ISSUE TITLE
Gazelle API: successful validation reported as undefined

### ISSUE THREAD

**Issue by qligier** [ahdis/matchbox#274]
In the Gazelle API, when no message is present, the status is computed to undefined instead of successful.

**Comment by qligier** [comment]
As discussed with Malo, the EVSClient will recalculate the status on its side and PASSED will be changed back to DONE_UNDEFINED.
We need to add an info message to properly pass the validation in the EVSClient.

**Comment by oliveregger** [comment]
also related to EHS-831

**Comment by oliveregger** [comment]
fixed in 3.9.3
