### ISSUE TITLE
GUI: defined validation urls to trigger the validation with predefined parameters and resources

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#288]
we would like to be able to trigger a validation directly on the GUI from an external website. this would allow to share links for validation without needing to store the validation results and also to have a collection for different validations:

https://test.ahdis.ch/matchboxv3/#/validate?profile=....&txServer=&resource=<base64enocded>

should set all the parameters, call the validation and  show the result

**Comment by qligier** [comment]
I'm unsure if Angular is capable of supporting query parameters after the hashtag, but something like https://test.ahdis.ch/matchboxv3/?profile=....&txServer=&resource=#/validate should work
