### ISSUE TITLE
Validation GUI: Error when clicking & copy validation url feature request

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#296]
1. when clicking in the GUI a validation error appears
2. Would it be possible to have a "copy url"  button to the right in actions, that a GET $validae request is constructed which we could you reuse and share?

<img width="935" alt="image" src="https://github.com/user-attachments/assets/6ae8b3b7-9a7f-4774-b4dd-4600dda690c6">

<img width="965" alt="image" src="https://github.com/user-attachments/assets/dad0dfe8-0ded-4c30-bc48-ac463f1f4c0c">

**Comment by qligier** [comment]
1. With the master version? Do you have details about the error in the console?
2. Sure.

**Comment by oliveregger** [comment]
1) with pulled main branch, does this help:

main-Q3C3ZD2F.js:1066 TypeError: Cannot read properties of undefined (reading 'forEach')
    at main-Q3C3ZD2F.js:1066:262073
    at Array.forEach (<anonymous>)
    at e.analyzeValidateOperationDefinition (main-Q3C3ZD2F.js:1066:262024)

**Comment by qligier** [comment]
Thanks.
Ok, it happens when there are no IG loaded in Matchbox.
