### ISSUE TITLE
Validation: Implement Ignore / Error handling with PolicyAdviseryFramework

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#307]
org.hl7.fhir.core introduced the PolicyAdviseryFramework to handle/ignore specific errors, warning.

we should try to use that framework too with matchbox's approach of error handling,.

**Comment by qligier** [comment]
Are we talking about this one? https://github.com/hapifhir/org.hl7.fhir.core/commit/56965820ea378447dbfe21e862123760ae8b4aec#diff-24fa08ddadb1ef4846e56ae49f2035ef35a24c438bd75df93c6cb230e90eb63eR852

That allows to suppress messages per FHIRPath (`Bundle.entry[2].resource/*Patient/1Pat-DM*/.address[0].country.extension[0].value.ofType(Coding)`), or validation message id (e.g. `Terminology_TX_Binding_NoSource`), but not by message itself.

**Comment by oliveregger** [comment]
yes but could we extend that framework that it would also work by message itself?

**Comment by qligier** [comment]
Not without modifying the BaseValidator to change the method `suppressMsg` calls. Also, we would need to construct the message before that check, instead of after.
So it would not be a better solution than now, in my opinion.
