### ISSUE TITLE
The StructureMap summary includes everything in the resource

### ISSUE THREAD

**Issue by qligier** [ahdis/matchbox#312]
In the GUI, we need to list all StructureMaps. We then use their name and url, nothing else.
The search operation, even in summary mode, returns almost everything, leading to considerable response sizes. E.g. for 20 StructureMaps, the response is 11442 lines long / 333kB. And we have 702 maps in total with only R4 loaded.

I was considering creating a StructureMap/$list operation to retrieve the bare minimal for this task. I'm not sure how to do it, though:

- Should we list all StructureMaps saved in the database? In that case, maps created through the FHIR API are not returned.
- In the `onlyOneEngine` mode, it's easy to list the maps loaded in the main engine.
- How should we support that when the `onlyOneEngine` mode is disabled? We can't list maps from engines. When pushing a map through the API, should we add it to the database?

Related to #131?

**Comment by oliveregger** [comment]
1) can we use graphql? see https://build.fhir.org/graphql.html and I think hapi-fhir is supporting it


>Should we list all StructureMaps saved in the database? In that case, maps created through the FHIR API are not returned.
the maps which are posted to matchbox a in the database or not? 

or are you talking about the transfrom API where the maps are directly provided?


>How should we support that when the onlyOneEngine mode is disabled? We can't list maps from engines. 

they are available in the database, that's how we get them in the transform operation:
 
https://github.com/ahdis/matchbox/blob/9ffdb26cf8526182b571ed0ef5464f05240178f7/matchbox-server/src/main/java/ch/ahdis/matchbox/util/MatchboxEngineSupport.java#L364
