### ISSUE TITLE
Add support for HL7 Terminology (THO) 6.1.0

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#313]
Add support for HL7 Terminology (THO) 6.1.0, see https://terminology.hl7.org/index.html

**Comment by qligier** [comment]
Is it an IG to load as we do with the FHIR Extensions Pack?

**Comment by oliveregger** [comment]
Yes but I think we should also provide it directly on the classpath instead of the old one and adapt all the references to use 6.1.0 as default
