### ISSUE TITLE
onlyOneEngine: additional engines created when dealing with StructureMaps

### ISSUE THREAD

**Issue by qligier** [ahdis/matchbox#316]
When dealing with StructureMaps, even if the `onlyOneEngine` is set, additional engines will be created.

E.g. when creating a map (POST /fhir/StructureMap) when the server is R4:
```
MappingLanguageInterceptor.incomingRequestPostProcessed
MappingLanguageInterceptor.parseMap
MatchboxEngine.parseMapR5
MatchboxEngine.getContextForFhirVersion
MatchboxEngine.getEngineR5
```

An R5 engine is created to parse the map.

I am unsure if we want to parse it with the main engine, if we need a special engine for that kind of processing, or if it's expected and alright.

**Comment by oliveregger** [comment]
for oneEngine it should always use this engine, i probably introduced a but somewhere ....
