### ISSUE TITLE
JSON POST Requests have a hard (too low) size limit

### ISSUE THREAD

**Issue by michaelonken** [ahdis/matchbox#33]
When trying to POST a JSON transaction Bundle larger than 5 MB to the server (including a DocumentReference which takes most of the space), the server responds:

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.21.5</center>
</body>
</html>
```

Since it is likely that there are reports taking a few MB the current limit should be higher. Attached an example request around 5 MB (it has not been tested what the actual limit is).

[report_request_too_large.zip](https://github.com/ahdis/matchbox/files/7853917/report_request_too_large.zip)

**Comment by oliveregger** [comment]
looks like this is the proxy from the docker compose setup, we need to increase client_max_body_size

http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size
https://www.nginx.com/resources/wiki/start/topics/examples/full/

**Comment by oliveregger** [comment]
the docker-compose setup uses nginx to proxy the request to the matchbox app server, nginx default limitation for body size is 1m, it is increased not with release v171 to 100m
