### ISSUE TITLE
Must be pilot error on running matchbox locally

### ISSUE THREAD

**Issue by stl-steve-moore** [ahdis/matchbox#35]
I tried running matchbox locally using these steps (MacOS, Docker Desktop)
mkdir data
mvn clean package -DskipTests
docker-compose up

I tried from the main branch (whatever was in there today) and from the 1.7.1 release. I get the same result each time.
* When the compose stack comes up, the log messages seem to show seem repeated database operations.
* When I browse to localhost:8080/matchbox, the viewer shows me an empty page. When I viewed the source, it was truly empty.
* When I browse to that page, you can see an exception being thrown. 

I am attaching output I captured using script.
[script.log](https://github.com/ahdis/matchbox/files/7936977/script.log)

**Comment by oliveregger** [comment]
Hi @stl-steve-moore , thanks for trying it out, it looks like everything startet up from the log, but you are right that http://localhost:8080/matchbox is not working :-(

1.) If you enter http://localhost:8080/matchbox/fhir you should get redirected to the swagger ui: http://localhost:8080/matchbox/fhir/swagger-ui/
2.) if you enter http://localhost:4300/matchbox-formfiller/#/CapabilityStatement you should see the base configuration of the server, if you enterhttp://localhost:4300/matchbox-formfiller/#/igs (or select IG's in the menu on the top right) you should see the ig's configured.

Let me know if you can access it like that.

**Comment by stl-steve-moore** [comment]
Aha, both 1 and 2 work for me. I am just starting and need to build my knowledge base and intuition. When the instructions told me to browse to /matchbox, I just followed blindly.

This gives me enough to make forward progress. I assume you will update the documentation or work some other magic.

Thanks for the quick turnaround.

**Comment by oliveregger** [comment]
yes, will improve the docs and probably also the setup, is difficult with two ports ... let me know if you need some more info and thanks for providing all the feedback!

**Comment by oliveregger** [comment]
@stl-steve-moore integrated with release 1.8.0 now the webapp directly on the matchbox, you can configure the ig's here:

- http://localhost:8080/matchbox/#/igs

and perform the validation here directly in the gui if you wish:

http://localhost:8080/matchbox/#/validate

you can also use the hosted instance at https://test.ahdis.ch/matchbox/#/
