### ISSUE TITLE
R5 transformations

### ISSUE THREAD

**Issue by joofio** [ahdis/matchbox#39]
Is it possible to use R5 structureDefs for mapping language usage?

Being trying with several different URL for R5 and always returning 
```
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-0389: Failed to call access method: org.hl7.fhir.exceptions.FHIRException: Unable to determine StructureDefinition for target type"
        }
    ]
```

Is it me? Or a missing feature atm?

**Comment by oliveregger** [comment]
@joofio matchbox currently supports only R4 StructureDefinitions. Internally the FHIR Mapping Language is based on R5, so it would be (or is) possible to use R5 StructureDefinitions, but matchbox would need to be adapted to work with a different version.

**Comment by joofio** [comment]
Thanks for the quick reply.
Something like that would be greatly appreciated!

If there is something I can do (even though Java is not my thing), feel free to reach out.

**Comment by oliveregger** [comment]
@joofio it has been a while, however matchbox now supports also working in R5 (or even in mixed mode R4 and R5). let me know if you are still interested.
