### ISSUE TITLE
system $validate operation not available in swagger-ui for POST 

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#44]
The swagger UI does not show a POST entry for $validate but a GET entry. Since you cannot the resource parameter as a GET, it should be a POST where the resource is provided in the body and the profile as a GET parameter.

http://ovh3.ihe-europe.net:8080/matchbox/fhir/swagger-ui/#/

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/2414516/166100217-824a07d8-6246-418f-b0ac-754e9e8954d0.png">

**Comment by oliveregger** [comment]
now the POST is added but it is not yet correct because we use a combination of POST and GET

**Comment by qligier** [comment]
It's back, but there are some 500 errors when browsing the Swagger UI due to a code mistake in MatchboxCapabilityStatementProvider.

![image](https://github.com/user-attachments/assets/701d14b4-70f5-46ce-a0fa-2fc011f87f00)
