### ISSUE TITLE
Prepare Matchbox for R5 support

### ISSUE THREAD

**Issue by costateixeira** [ahdis/matchbox#55]

**Comment by oliveregger** [comment]
see also https://github.com/ahdis/matchbox/blob/main/matchbox-server/src/main/java/ch/ahdis/fhir/hapi/jpa/validation/ValidationProvider.java#L109

**Comment by qligier** [comment]
A R5 IG:
https://build.fhir.org/ig/HL7EE/ig-ee-base/

https://www.fhir.org/guides/registry/
