### ISSUE TITLE
request to support R4B

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#65]
We would like to use Matchbox with FHIR resources in fhirVersion 4.3.0 with R4B standard
Unfortunately, the matchbox v2.3.0 works with HAPI FHIR 6.0.0 and it seems that only the 6.2.0 can manage R4B.

We would like to know when Matchbox will be upgraded with HAPI FHIR 6.2.0 ?

**Comment by qligier** [comment]
Is R4B still needed?

**Comment by oliveregger** [comment]
available since version 3.9.1
