### ISSUE TITLE
Validation Medication Card

### ISSUE THREAD

**Issue by ziegm** [ahdis/matchbox#8]
The validation of the Medication Card document with the IG Publisher (v1.1.79) does not result in any errors.

The validation of the same document with the EVS-Client shows following error:
Bundle.entry:Composition: minimum required = 1, but only found 0 (from http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationcard)
see here: https://ehealthsuisse.ihe-europe.net/EVSClient/detailedResult.seam?type=FHIR&oid=1.3.6.1.4.1.12559.11.25.1.1350359

**Comment by ziegm** [comment]
Validation of the Medication Card document of the CH EMED IG (2-7-MedicationCard.json):
https://ehealthsuisse.ihe-europe.net/EVSClient/detailedResult.seam?type=FHIR&oid=1.3.6.1.4.1.12559.11.25.1.1350390

**Comment by oliveregger** [comment]
will be fixed with next release

**Comment by oliveregger** [comment]
fixed with release 1.4.0
