### ISSUE TITLE
improve ci-build

### ISSUE THREAD

**Issue by oliveregger** [ahdis/matchbox#83]
- publish on tag also matchbox-engine on central repository
- publish on tag the apidocs directly from ci-build
- publish on tag also the docs

for creating a pull request or on commit
- introduce the CodeQL into the ci-build

general setup
- enable dependabot alerts

**Comment by oliveregger** [comment]
related to #79

**Comment by qligier** [comment]
Dependabot alerts have been enabled (Settings > [Code security and analysis](https://github.com/ahdis/matchbox/settings/security_analysis))

**Comment by qligier** [comment]
All these have been implemented.
